{{- if .Values.persistence.relationalJdbc.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.persistence.relationalJdbc.secret.name | default "polaris-persistence-secret" }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "polaris.labels" . | nindent 4 }}
    app: polaris
    component: persistence
type: Opaque
stringData:
  username: {{ .Values.persistence.relationalJdbc.secret.username | quote }}
  password: {{ .Values.persistence.relationalJdbc.secret.password | quote }}
  jdbcUrl: {{ .Values.persistence.relationalJdbc.secret.jdbcUrl | quote }}
  bootstrapCredentials: {{ .Values.persistence.relationalJdbc.secret.bootstrapCredentials | quote }}
{{- end }}
